Add model client
Seba-85/invoicing-app pull request #17
Opened 2023-08-10 20:33 UTC by Seba-85

2023-08-10 21:40 UTC, damianpllatek requested changes
Drobne uwagi z pustymi liniami i plik do usunięcia. Dobrą praktyką jest robić migrację na osobnym PR, ale w tym przypadku możę być. W realnym projekcie nie przejdzie. 

Tak to jest ok :)

2023-08-10 21:40 UTC, damianpllatek commented on app/controllers/clients_controller.rb
> +
Pusta linia do usunięcia.

2023-08-10 21:40 UTC, damianpllatek commented on app/controllers/clients_controller.rb
> +
Dwie puste linie do usunięcia

2023-08-10 21:40 UTC, damianpllatek commented on app/controllers/clients_controller.rb
> +    params.require(:client).permit(:company_name, :owner_name, :owner_last_name, :street, :postal_code, :city, :province, :country, :tax_number, :regon, :email)
Warto by było złamać linie, aby nie przekraczało 120 znaków.

2023-08-10 21:40 UTC, damianpllatek commented on er.clients.find(params[id])
> +=> [[32m#<Client:0x0000026f794fceb0[0m
Tego pliku nie powinno być - do usunięcia

2023-08-10 21:40 UTC, damianpllatek commented on app/controllers/clients_controller.rb
> +  before_action :find_user
Na wszystkich akcjach ma być user?

2023-08-10 22:24 UTC, Seba-85 commented on app/controllers/clients_controller.rb
> +  before_action :find_user
Wychodzi mi, że na wszystkich musi być, sprawdzałem akcja po akcji. Aczkolwiek mogę się mylić :)

2023-08-11 06:19 UTC, damianpllatek approved these changes

2023-08-11 06:19 UTC, damianpllatek commented on app/controllers/clients_controller.rb
> +  before_action :find_user
Na wszystkich akcjach ma być user?

2023-08-15 07:22 UTC, merged